import type { Category, Supplier } from './types';

export const mockCategories: Category[] = [
  {
    id: 'cat-1',
    name: 'Bahan Pokok',
    slug: 'bahan-pokok',
    icon: 'Wheat',
    parent_id: null,
  },
  {
    id: 'cat-2',
    name: 'Sembako & Grocery',
    slug: 'sembako-grocery',
    icon: 'ShoppingBag',
    parent_id: null,
  },
  {
    id: 'cat-3',
    name: 'Pernak-pernik & Aksesoris',
    slug: 'pernak-pernik-aksesoris',
    icon: 'Gift',
    parent_id: null,
  },
  {
    id: 'cat-4',
    name: 'Fashion & Tekstil',
    slug: 'fashion-tekstil',
    icon: 'Shirt',
    parent_id: null,
  },
];

export const mockSuppliers: Supplier[] = [
  {
    id: 'sup-01',
    name: 'PT Beras Sejahtera Nusantara',
    slug: 'pt-beras-sejahtera-nusantara',
    description:
      'Supplier beras premium langsung dari petani di Karawang dan Subang. Menyediakan beras putih, beras merah, dan beras organik dalam kemasan 5kg, 10kg, dan 25kg. Sudah berpengalaman lebih dari 15 tahun melayani pasar tradisional dan modern di Jabodetabek.',
    category_ids: ['cat-1'],
    location_city: 'Jakarta',
    location_province: 'DKI Jakarta',
    contact_whatsapp: '6281234560001',
    contact_phone: '02145678901',
    contact_address: 'Jl. Raya Pasar Induk No. 12, Kramat Jati, Jakarta Timur',
    min_order: '100 kg',
    payment_methods: ['Transfer Bank', 'COD', 'QRIS'],
    rating: 4.8,
    kurasi_notes:
      'Supplier terpercaya dengan track record 15 tahun. Beras berkualitas tinggi langsung dari petani binaan. Harga kompetitif dan pengiriman tepat waktu ke seluruh Jabodetabek.',
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
      'https://images.unsplash.com/photo-1536304993881-460ea32321d4?w=400',
      'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400',
    ],
    created_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 'sup-02',
    name: 'UD Minyak Jaya Abadi',
    slug: 'ud-minyak-jaya-abadi',
    description:
      'Distributor minyak goreng curah dan kemasan dari berbagai merek ternama. Melayani grosir untuk warung, restoran, dan UMKM di area Jawa Timur. Tersedia minyak goreng sawit, minyak kelapa, dan minyak wijen.',
    category_ids: ['cat-1', 'cat-2'],
    location_city: 'Surabaya',
    location_province: 'Jawa Timur',
    contact_whatsapp: '6281234560002',
    contact_phone: '03156789012',
    contact_address: 'Jl. Perak Barat No. 45, Krembangan, Surabaya',
    min_order: '1 karton (12 liter)',
    payment_methods: ['Transfer Bank', 'COD'],
    rating: 4.5,
    kurasi_notes:
      'Harga paling kompetitif di Surabaya untuk minyak goreng grosir. Stok selalu tersedia dan bisa kirim dalam 24 jam untuk area Surabaya dan sekitarnya.',
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400',
      'https://images.unsplash.com/photo-1620706857370-e1b9770e8bb1?w=400',
    ],
    created_at: '2025-01-15T10:30:00Z',
  },
  {
    id: 'sup-03',
    name: 'CV Gula Manis Semarang',
    slug: 'cv-gula-manis-semarang',
    description:
      'Produsen dan distributor gula pasir, gula merah, dan gula aren asli Jawa Tengah. Produk kami diproses secara higienis dan sudah bersertifikat BPOM. Cocok untuk kebutuhan industri makanan, kafe, dan warung makan.',
    category_ids: ['cat-1'],
    location_city: 'Semarang',
    location_province: 'Jawa Tengah',
    contact_whatsapp: '6281234560003',
    contact_phone: '02467890123',
    contact_address: 'Jl. Kaligawe Raya KM 5, Genuk, Semarang',
    min_order: '50 kg',
    payment_methods: ['Transfer Bank', 'QRIS', 'Tempo 7 Hari'],
    rating: 4.3,
    kurasi_notes:
      'Gula aren dan gula merah yang dihasilkan berkualitas premium, sangat cocok untuk bisnis FnB. Sudah bersertifikat BPOM dan halal MUI. Sistem pembayaran tempo memudahkan UMKM.',
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400',
      'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400',
      'https://images.unsplash.com/photo-1604431696980-07e518647610?w=400',
    ],
    created_at: '2025-02-01T09:00:00Z',
  },
  {
    id: 'sup-04',
    name: 'Toko Sembako Berkah Bandung',
    slug: 'toko-sembako-berkah-bandung',
    description:
      'Grosir sembako lengkap meliputi beras, minyak goreng, tepung terigu, gula, telur, dan bumbu dapur. Melayani pembelian grosir untuk warung, katering, dan usaha makanan di wilayah Bandung Raya.',
    category_ids: ['cat-2'],
    location_city: 'Bandung',
    location_province: 'Jawa Barat',
    contact_whatsapp: '6281234560004',
    contact_phone: '02278901234',
    contact_address: 'Jl. Ahmad Yani No. 88, Kiaracondong, Bandung',
    min_order: 'Rp 500.000',
    payment_methods: ['Transfer Bank', 'COD', 'QRIS'],
    rating: 4.6,
    kurasi_notes:
      'One-stop shopping untuk kebutuhan sembako grosir. Harga stabil dan transparan. Pemilik sangat responsif di WhatsApp dan bisa atur pengiriman dengan cepat.',
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400',
      'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=400',
      'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=400',
    ],
    created_at: '2025-02-10T11:00:00Z',
  },
  {
    id: 'sup-05',
    name: 'UD Tepung Makmur Jogja',
    slug: 'ud-tepung-makmur-jogja',
    description:
      'Distributor tepung terigu, tepung beras, tepung tapioka, dan berbagai jenis tepung lainnya. Menyuplai ke bakeri, UMKM kue, dan industri makanan ringan di DIY dan Jawa Tengah.',
    category_ids: ['cat-1', 'cat-2'],
    location_city: 'Yogyakarta',
    location_province: 'DI Yogyakarta',
    contact_whatsapp: '6281234560005',
    contact_phone: '02749012345',
    contact_address: 'Jl. Parangtritis KM 8, Bantul, Yogyakarta',
    min_order: '25 kg',
    payment_methods: ['Transfer Bank', 'COD'],
    rating: 4.2,
    kurasi_notes:
      'Pilihan tepung sangat lengkap, dari tepung terigu protein tinggi sampai tepung beras gluten-free. Cocok untuk UMKM bakeri dan produsen makanan ringan. Harga grosir sangat bersaing.',
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400',
      'https://images.unsplash.com/photo-1556767576-5ec41e3239ea?w=400',
    ],
    created_at: '2025-02-20T08:30:00Z',
  },
  {
    id: 'sup-06',
    name: 'PT Bumbu Rempah Nusantara',
    slug: 'pt-bumbu-rempah-nusantara',
    description:
      'Supplier bumbu rempah-rempah khas Indonesia: kunyit, jahe, lengkuas, serai, daun salam, dan bumbu jadi siap pakai. Produk segar dan kering tersedia. Melayani restoran, katering, dan produsen makanan skala nasional.',
    category_ids: ['cat-2'],
    location_city: 'Surabaya',
    location_province: 'Jawa Timur',
    contact_whatsapp: '6281234560006',
    contact_phone: '03160123456',
    contact_address: 'Jl. Rungkut Industri III No. 22, Surabaya',
    min_order: '10 kg',
    payment_methods: ['Transfer Bank', 'QRIS', 'Tempo 14 Hari'],
    rating: 4.7,
    kurasi_notes:
      'Kualitas rempah sangat konsisten dan segar. Sudah menjadi supplier tetap banyak restoran besar di Surabaya. Sistem tempo 14 hari sangat membantu cash flow bisnis FnB.',
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400',
      'https://images.unsplash.com/photo-1532336414036-cf2215468350?w=400',
      'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=400',
    ],
    created_at: '2025-03-01T07:00:00Z',
  },
  {
    id: 'sup-07',
    name: 'Aksesoris Mutiara Tanah Abang',
    slug: 'aksesoris-mutiara-tanah-abang',
    description:
      'Grosir aksesoris wanita: kalung, gelang, anting, bros, jepit rambut, dan ikat rambut. Barang import dan lokal dengan kualitas terjamin. Tersedia ribuan model terbaru setiap bulannya. Cocok untuk reseller online shop dan toko aksesoris.',
    category_ids: ['cat-3'],
    location_city: 'Jakarta',
    location_province: 'DKI Jakarta',
    contact_whatsapp: '6281234560007',
    contact_phone: '02134567890',
    contact_address: 'Blok A Lt. 3 No. 156, Pasar Tanah Abang, Jakarta Pusat',
    min_order: '3 lusin',
    payment_methods: ['Transfer Bank', 'COD', 'QRIS'],
    rating: 4.4,
    kurasi_notes:
      'Variasi model sangat banyak dan selalu update trend terbaru. Harga grosir sangat murah, cocok untuk reseller dengan margin bagus. Bisa mix model dalam 1 lusin.',
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1515562141589-67f0d569b6f5?w=400',
      'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=400',
    ],
    created_at: '2025-03-05T10:00:00Z',
  },
  {
    id: 'sup-08',
    name: 'CV Souvenir Kreatif Jogja',
    slug: 'cv-souvenir-kreatif-jogja',
    description:
      'Produsen souvenir dan pernak-pernik handmade khas Yogyakarta. Menyediakan gantungan kunci, tote bag, pouch batik, kipas, dan berbagai souvenir custom untuk acara pernikahan, seminar, dan corporate event.',
    category_ids: ['cat-3'],
    location_city: 'Yogyakarta',
    location_province: 'DI Yogyakarta',
    contact_whatsapp: '6281234560008',
    contact_phone: '02745678901',
    contact_address: 'Jl. Malioboro No. 201, Gedongtengen, Yogyakarta',
    min_order: '50 pcs',
    payment_methods: ['Transfer Bank', 'DP 50%'],
    rating: 4.1,
    kurasi_notes:
      'Produk handmade berkualitas dengan sentuhan budaya Jogja. Bisa custom desain dan logo. Harga sangat terjangkau untuk souvenir acara. Pengerjaan rapi dan tepat waktu.',
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1513519245088-0e12902e35ca?w=400',
      'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=400',
      'https://images.unsplash.com/photo-1528396518501-b53b655eb9b3?w=400',
    ],
    created_at: '2025-03-10T09:00:00Z',
  },
  {
    id: 'sup-09',
    name: 'Toko Mainan Edukatif Ceria',
    slug: 'toko-mainan-edukatif-ceria',
    description:
      'Grosir mainan edukatif anak-anak: puzzle kayu, balok susun, flash card, mainan montessori, dan alat tulis lucu. Barang berkualitas SNI dan aman untuk anak. Melayani toko mainan, playgroup, dan reseller online.',
    category_ids: ['cat-3'],
    location_city: 'Bandung',
    location_province: 'Jawa Barat',
    contact_whatsapp: '6281234560009',
    contact_phone: '02256789012',
    contact_address: 'Jl. Cihampelas No. 77, Coblong, Bandung',
    min_order: '1 lusin',
    payment_methods: ['Transfer Bank', 'COD', 'QRIS'],
    rating: 4.5,
    kurasi_notes:
      'Semua mainan sudah bersertifikat SNI dan aman untuk anak. Kemasan rapi dan siap jual. Banyak reseller yang sudah berhasil jualan produk dari sini dengan margin 40-60%.',
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=400',
      'https://images.unsplash.com/photo-1560859251-d563a49c5e4a?w=400',
    ],
    created_at: '2025-03-15T08:00:00Z',
  },
  {
    id: 'sup-10',
    name: 'Konveksi Maju Bersama Solo',
    slug: 'konveksi-maju-bersama-solo',
    description:
      'Konveksi kaos, polo shirt, jaket, dan seragam dengan kualitas ekspor. Melayani pesanan custom dari 24 pcs dengan berbagai pilihan bahan: cotton combed 30s, CVC, dan drifit. Sablon plastisol, DTF, dan bordir tersedia.',
    category_ids: ['cat-4'],
    location_city: 'Surakarta',
    location_province: 'Jawa Tengah',
    contact_whatsapp: '6281234560010',
    contact_phone: '02718901234',
    contact_address: 'Jl. Dr. Rajiman No. 310, Laweyan, Surakarta',
    min_order: '24 pcs',
    payment_methods: ['Transfer Bank', 'DP 50%'],
    rating: 4.6,
    kurasi_notes:
      'Kualitas jahitan rapi setara ekspor. Bahan cotton combed 30s yang digunakan sangat nyaman. Harga mulai Rp35.000/pcs untuk order di atas 100 pcs. Pengerjaan 7-14 hari kerja.',
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=400',
      'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=400',
      'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=400',
    ],
    created_at: '2025-03-20T10:00:00Z',
  },
  {
    id: 'sup-11',
    name: 'Batik Pekalongan Asli Bu Sari',
    slug: 'batik-pekalongan-asli-bu-sari',
    description:
      'Produsen batik tulis dan batik cap asli Pekalongan. Tersedia kain batik, kemeja batik pria, blouse batik wanita, dan seragam batik kantor. Motif tradisional dan modern dengan pewarnaan alam dan sintetis.',
    category_ids: ['cat-4'],
    location_city: 'Pekalongan',
    location_province: 'Jawa Tengah',
    contact_whatsapp: '6281234560011',
    contact_phone: '02859012345',
    contact_address: 'Jl. Teratai No. 15, Kauman, Pekalongan',
    min_order: '10 pcs',
    payment_methods: ['Transfer Bank', 'COD', 'Tempo 7 Hari'],
    rating: 5.0,
    kurasi_notes:
      'Batik tulis asli dengan pewarnaan alam yang sangat indah. Bu Sari sudah 30 tahun di industri batik. Produk premium dengan harga langsung pengrajin. Sangat direkomendasikan untuk reseller batik.',
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1569517282132-25d22f4573e6?w=400',
      'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400',
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400',
    ],
    created_at: '2025-04-01T07:30:00Z',
  },
  {
    id: 'sup-12',
    name: 'Grosir Hijab Amanah Tasikmalaya',
    slug: 'grosir-hijab-amanah-tasikmalaya',
    description:
      'Produsen dan grosir hijab, kerudung, pashmina, dan ciput dari Tasikmalaya. Bahan voal, ceruti, jersey, dan diamond. Tersedia polos dan motif. Harga mulai Rp12.000/pcs untuk pembelian grosir. Cocok untuk reseller hijab online dan offline.',
    category_ids: ['cat-4'],
    location_city: 'Tasikmalaya',
    location_province: 'Jawa Barat',
    contact_whatsapp: '6281234560012',
    contact_phone: '02650123456',
    contact_address: 'Jl. Manonjaya No. 55, Kawalu, Tasikmalaya',
    min_order: '5 lusin',
    payment_methods: ['Transfer Bank', 'QRIS', 'COD'],
    rating: 3.9,
    kurasi_notes:
      'Harga paling murah se-Indonesia untuk hijab grosir karena langsung dari sentra produksi Tasikmalaya. Bahan bagus dan jahitan rapi. Banyak reseller yang sukses mulai dari sini.',
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1590735213920-68192a487bc2?w=400',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=400',
    ],
    created_at: '2025-04-05T09:00:00Z',
  },
];
