import type { Supplier, Category, Review } from './types';

export const mockCategories: Category[] = [
  { id: 'cat-1', name: 'Bahan Pokok', slug: 'bahan-pokok', icon: 'Wheat', parent_id: null },
  { id: 'cat-2', name: 'Sembako & Grocery', slug: 'sembako-grocery', icon: 'ShoppingBag', parent_id: null },
  { id: 'cat-3', name: 'Pernak-pernik & Aksesoris', slug: 'pernak-pernik', icon: 'Gift', parent_id: null },
  { id: 'cat-4', name: 'Fashion & Tekstil', slug: 'fashion-tekstil', icon: 'Shirt', parent_id: null },
];

export const mockSuppliers: Supplier[] = [
  {
    id: 'sup-1',
    name: 'PT Beras Sejahtera Nusantara',
    slug: 'pt-beras-sejahtera-nusantara',
    owner_name: 'Hendra Gunawan',
    email: 'hendra@berassejahtera.co.id',
    description: 'Supplier beras premium langsung dari petani di Karawang dan Subang. Menyediakan beras putih, beras merah, dan beras organik dalam kemasan 5kg, 10kg, dan 25kg. Sudah berpengalaman lebih dari 15 tahun melayani pasar tradisional, minimarket, dan catering.',
    category_ids: ['cat-1'],
    location_city: 'Jakarta',
    location_province: 'DKI Jakarta',
    price_level: 'affordable',
    contact_whatsapp: '6281234560001',
    contact_phone: '02145678901',
    contact_address: 'Jl. Raya Pasar Induk No. 12, Kramat Jati, Jakarta Timur',
    social_tiktok: 'https://tiktok.com/@berassejahtera',
    social_instagram: 'https://instagram.com/berassejahtera',
    social_wa_business: 'https://wa.me/6281234560001',
    shop_shopee: 'https://shopee.co.id/berassejahtera',
    shop_tokopedia: 'https://tokopedia.com/berassejahtera',
    rating: 4.8,
    review_count: 24,
    kurasi_notes: 'Telah kami verifikasi langsung ke gudang. Kualitas beras konsisten, harga kompetitif untuk pembelian ≥ 100kg. Responsivitas WhatsApp sangat baik (< 1 jam).',
    status: 'active',
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600', 'https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?w=600', 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600'],
    created_at: '2026-01-15T08:00:00Z',
  },
  {
    id: 'sup-2',
    name: 'UD Minyak Jaya Abadi',
    slug: 'ud-minyak-jaya-abadi',
    owner_name: 'Suharto Wijaya',
    email: 'suharto@minyakjaya.com',
    description: 'Distributor minyak goreng curah dan kemasan dari berbagai merek terkemuka. Melayani warung, restoran, dan usaha katering. Harga grosir tersedia untuk pembelian ≥ 50 liter. Pengiriman ke seluruh Jawa Timur.',
    category_ids: ['cat-1'],
    location_city: 'Surabaya',
    location_province: 'Jawa Timur',
    price_level: 'budget',
    contact_whatsapp: '6281234560002',
    contact_phone: '03198765432',
    contact_address: 'Jl. Pabean Raya No. 45, Pabean Cantian, Surabaya',
    social_instagram: 'https://instagram.com/minyakjayaabadi',
    social_wa_business: 'https://wa.me/6281234560002',
    shop_shopee: 'https://shopee.co.id/minyakjaya',
    rating: 4.5,
    review_count: 18,
    kurasi_notes: 'Distributor resmi dari beberapa brand minyak goreng nasional. Harga paling kompetitif di Surabaya untuk skala grosir. Gudang luas dan stok selalu tersedia.',
    status: 'active',
    images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600', 'https://images.unsplash.com/photo-1585238342024-78d387f4a707?w=600'],
    created_at: '2026-01-20T08:00:00Z',
  },
  {
    id: 'sup-3',
    name: 'CV Gula Manis Semarang',
    slug: 'cv-gula-manis-semarang',
    owner_name: 'Budiman Santoso',
    email: 'budiman@gulamanis.id',
    description: 'Produsen dan distributor gula pasir, gula merah, dan gula aren premium. Bahan baku langsung dari petani tebu Jawa Tengah. Kemasan tersedia dari 1kg hingga 50kg.',
    category_ids: ['cat-1', 'cat-2'],
    location_city: 'Semarang',
    location_province: 'Jawa Tengah',
    price_level: 'affordable',
    contact_whatsapp: '6281234560003',
    contact_phone: '02476543210',
    contact_address: 'Jl. Kaligawe Raya Km. 5, Genuk, Semarang',
    social_facebook: 'https://facebook.com/gulamanissemarang',
    social_instagram: 'https://instagram.com/gulamanis.smg',
    shop_tokopedia: 'https://tokopedia.com/gulamanis',
    shop_shopee: 'https://shopee.co.id/gulamanis',
    rating: 4.3,
    review_count: 12,
    kurasi_notes: 'Kualitas gula pasir sangat konsisten, kadar sukrosa tinggi. Sertifikat SNI dan hasil lab sudah kami cek.',
    status: 'active',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600', 'https://images.unsplash.com/photo-1587049633312-d628ae50a8ae?w=600'],
    created_at: '2026-02-01T08:00:00Z',
  },
  {
    id: 'sup-4',
    name: 'Toko Sembako Berkah Bandung',
    slug: 'toko-sembako-berkah-bandung',
    owner_name: 'Ratna Dewi',
    email: 'ratna@sembakoberkah.com',
    description: 'Grosir sembako lengkap: beras, minyak, gula, tepung, kopi, teh, susu. Melayani warung, minimarket, dan kantin. Harga distributor langsung, pengiriman H+1 untuk area Bandung Raya.',
    category_ids: ['cat-2'],
    location_city: 'Bandung',
    location_province: 'Jawa Barat',
    price_level: 'budget',
    contact_whatsapp: '6281234560004',
    contact_phone: '02212345678',
    contact_address: 'Jl. Soekarno Hatta No. 200, Bandung',
    social_instagram: 'https://instagram.com/sembakoberkah',
    social_tiktok: 'https://tiktok.com/@sembakoberkah',
    shop_shopee: 'https://shopee.co.id/sembakoberkah',
    shop_tokopedia: 'https://tokopedia.com/sembakoberkah',
    rating: 4.6,
    review_count: 31,
    kurasi_notes: 'Stok sangat lengkap dan selalu ready. Harga sangat bersaing untuk area Bandung. Rating pengiriman 4.9/5 dari pelanggan tetap.',
    status: 'active',
    images: ['https://images.unsplash.com/photo-1542838132-92c53300491e?w=600', 'https://images.unsplash.com/photo-1609709295948-17d77cb2a69b?w=600'],
    created_at: '2026-02-05T08:00:00Z',
  },
  {
    id: 'sup-5',
    name: 'UD Tepung Makmur Jogja',
    slug: 'ud-tepung-makmur-jogja',
    owner_name: 'Agus Prasetyo',
    email: 'agus@tepungmakmur.co.id',
    description: 'Supplier tepung terigu, tepung beras, tepung tapioka, dan tepung bumbu. Memasok untuk bakeri, usaha gorengan, dan industri makanan rumahan. Tersedia kemasan 1kg, 5kg, dan karung 25kg.',
    category_ids: ['cat-2'],
    location_city: 'Yogyakarta',
    location_province: 'DI Yogyakarta',
    price_level: 'midrange',
    contact_whatsapp: '6281234560005',
    contact_phone: '02741234567',
    contact_address: 'Jl. Magelang Km. 8, Mlati, Sleman, Yogyakarta',
    social_instagram: 'https://instagram.com/tepungmakmur',
    shop_tokopedia: 'https://tokopedia.com/tepungmakmur',
    shop_shopee: 'https://shopee.co.id/tepungmakmur',
    rating: 4.2,
    review_count: 9,
    kurasi_notes: 'Kualitas tepung protein tinggi sangat baik untuk bakeri. Cocok untuk usaha yang tidak mau ambil risiko kualitas.',
    status: 'active',
    images: ['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600', 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600'],
    created_at: '2026-02-10T08:00:00Z',
  },
  {
    id: 'sup-6',
    name: 'PT Bumbu Rempah Nusantara',
    slug: 'pt-bumbu-rempah-nusantara',
    owner_name: 'Sri Wahyuni',
    email: 'sri@bumbunusantara.id',
    description: 'Produsen bumbu rempah giling, bumbu instan, dan bahan baku bumbu kering. Produk tanpa pengawet, kemasan vakum. Cocok untuk catering, restoran, dan produksi skala rumahan.',
    category_ids: ['cat-2'],
    location_city: 'Surabaya',
    location_province: 'Jawa Timur',
    price_level: 'midrange',
    contact_whatsapp: '6281234560006',
    contact_phone: '03187654321',
    contact_address: 'Jl. Wonokromo No. 88, Surabaya',
    social_tiktok: 'https://tiktok.com/@bumbunusantara',
    social_instagram: 'https://instagram.com/bumbunusantara',
    social_facebook: 'https://facebook.com/bumbunusantara',
    shop_shopee: 'https://shopee.co.id/bumbunusantara',
    shop_tokopedia: 'https://tokopedia.com/bumbunusantara',
    shop_tiktok: 'https://tiktokshop.com/bumbunusantara',
    rating: 4.7,
    review_count: 45,
    kurasi_notes: 'Produk unggulan! Bumbu giling segar tanpa MSG, tersertifikasi halal MUI. Sudah supply ke 20+ restoran di Surabaya.',
    status: 'active',
    images: ['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600', 'https://images.unsplash.com/photo-1583195764036-46c4b6a96a49?w=600', 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=600'],
    created_at: '2026-02-15T08:00:00Z',
  },
  {
    id: 'sup-7',
    name: 'Aksesoris Mutiara Tanah Abang',
    slug: 'aksesoris-mutiara-tanah-abang',
    owner_name: 'Linda Susanti',
    email: 'linda@mutiaraaksesoris.com',
    description: 'Grosir aksesoris fashion wanita: kalung, gelang, anting, bros, ikat rambut. Koleksi 500+ item, update tiap minggu. MOQ rendah mulai 10 pcs per item.',
    category_ids: ['cat-3'],
    location_city: 'Jakarta',
    location_province: 'DKI Jakarta',
    price_level: 'budget',
    contact_whatsapp: '6281234560007',
    contact_phone: '02187654321',
    contact_address: 'Pasar Tanah Abang Blok A, Lt. 3, No. 125, Jakarta Pusat',
    social_tiktok: 'https://tiktok.com/@mutiaraaksesoris',
    social_instagram: 'https://instagram.com/mutiara.aksesoris',
    social_wa_business: 'https://wa.me/6281234560007',
    shop_shopee: 'https://shopee.co.id/mutiaraaksesoris',
    shop_tokopedia: 'https://tokopedia.com/mutiaraaksesoris',
    shop_tiktok: 'https://tiktokshop.com/mutiaraaksesoris',
    rating: 4.4,
    review_count: 67,
    kurasi_notes: 'Koleksi terlengkap di Tanah Abang. Tim aktif di TikTok dengan 50K+ followers — produk terus viral.',
    status: 'active',
    images: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600', 'https://images.unsplash.com/photo-1608042314453-ae338d680c1c?w=600'],
    created_at: '2026-02-20T08:00:00Z',
  },
  {
    id: 'sup-8',
    name: 'CV Souvenir Kreatif Jogja',
    slug: 'cv-souvenir-kreatif-jogja',
    owner_name: 'Dian Pratiwi',
    email: 'dian@souvenirjogja.id',
    description: 'Produsen souvenir unik khas Yogyakarta: batik mini, wayang kecil, gantungan kunci, magnet kulkas, dekorasi etnik. Custom order untuk corporate gift dan souvenir pernikahan tersedia.',
    category_ids: ['cat-3'],
    location_city: 'Yogyakarta',
    location_province: 'DI Yogyakarta',
    price_level: 'midrange',
    contact_whatsapp: '6281234560008',
    contact_phone: '02744321098',
    contact_address: 'Jl. Malioboro No. 150, Gedongtengen, Yogyakarta',
    social_instagram: 'https://instagram.com/souvenirkreatifjogja',
    social_tiktok: 'https://tiktok.com/@souvenirjogja',
    social_facebook: 'https://facebook.com/souvenirkreatifjogja',
    shop_shopee: 'https://shopee.co.id/souvenirjogja',
    shop_tokopedia: 'https://tokopedia.com/souvenirjogja',
    shop_lazada: 'https://lazada.co.id/souvenirjogja',
    rating: 4.1,
    review_count: 28,
    kurasi_notes: 'Produk autentik buatan pengrajin lokal Yogyakarta. Custom order diproses cepat 5-7 hari kerja untuk 100-500 pcs.',
    status: 'active',
    images: ['https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],
    created_at: '2026-02-25T08:00:00Z',
  },
  {
    id: 'sup-9',
    name: 'Toko Mainan Edukatif Ceria',
    slug: 'toko-mainan-edukatif-ceria',
    owner_name: 'Firmansyah Hakim',
    email: 'firman@mainanceria.com',
    description: 'Grosir mainan edukatif anak: puzzle, balok kayu, alat masak mainan, boneka, dan buku anak. Semua produk lulus SNI dan bebas bahan berbahaya.',
    category_ids: ['cat-3'],
    location_city: 'Bandung',
    location_province: 'Jawa Barat',
    price_level: 'affordable',
    contact_whatsapp: '6281234560009',
    contact_phone: '02287654321',
    contact_address: 'Jl. Cihampelas No. 85, Bandung',
    social_instagram: 'https://instagram.com/mainanceria',
    social_tiktok: 'https://tiktok.com/@mainanceria',
    social_wa_business: 'https://wa.me/6281234560009',
    shop_shopee: 'https://shopee.co.id/mainanceria',
    shop_tokopedia: 'https://tokopedia.com/mainanceria',
    shop_blibli: 'https://blibli.com/mainanceria',
    rating: 4.5,
    review_count: 52,
    kurasi_notes: 'Sertifikasi SNI lengkap dan kami verifikasi sendiri. Packaging menarik, cocok untuk dijual kembali tanpa perlu repacking.',
    status: 'active',
    images: ['https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=600', 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600'],
    created_at: '2026-03-01T08:00:00Z',
  },
  {
    id: 'sup-10',
    name: 'Konveksi Maju Bersama Solo',
    slug: 'konveksi-maju-bersama-solo',
    owner_name: 'Bambang Wicaksono',
    email: 'bambang@konveksimaju.id',
    description: 'Konveksi pakaian: kaos polos, kemeja, hoodie, celana, seragam. Custom sablon, bordir, dan label tersedia. MOQ 12 pcs per desain.',
    category_ids: ['cat-4'],
    location_city: 'Surakarta',
    location_province: 'Jawa Tengah',
    price_level: 'affordable',
    contact_whatsapp: '6281234560010',
    contact_phone: '02714321098',
    contact_address: 'Jl. Veteran No. 55, Serengan, Solo',
    social_instagram: 'https://instagram.com/konveksimajusolo',
    social_facebook: 'https://facebook.com/konveksimajusolo',
    social_wa_business: 'https://wa.me/6281234560010',
    shop_tokopedia: 'https://tokopedia.com/konveksimajusolo',
    shop_shopee: 'https://shopee.co.id/konveksimajusolo',
    rating: 4.6,
    review_count: 39,
    kurasi_notes: 'Mesin produksi modern, jahitan rapi. Turnaround 7-10 hari untuk order 100-500 pcs. Direkomendasikan untuk pemula dropship.',
    status: 'active',
    images: ['https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600', 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=600'],
    created_at: '2026-03-05T08:00:00Z',
  },
  {
    id: 'sup-11',
    name: 'Batik Pekalongan Asli Bu Sari',
    slug: 'batik-pekalongan-asli-bu-sari',
    owner_name: 'Sari Rahayu',
    email: 'sari@batikpekalongan.id',
    description: 'Produsen batik tulis dan batik cap Pekalongan asli. Motif klasik dan modern, pewarna alami tersedia. MOQ 6 potong per motif.',
    category_ids: ['cat-4'],
    location_city: 'Pekalongan',
    location_province: 'Jawa Tengah',
    price_level: 'premium',
    contact_whatsapp: '6281234560011',
    contact_phone: '02854321098',
    contact_address: 'Jl. Batik Raya No. 25, Kauman, Pekalongan',
    social_instagram: 'https://instagram.com/batikpekalongan_asli',
    social_tiktok: 'https://tiktok.com/@batikpekalongan',
    social_facebook: 'https://facebook.com/batikpekalonganasli',
    social_wa_business: 'https://wa.me/6281234560011',
    shop_tokopedia: 'https://tokopedia.com/batikpekalongan',
    shop_shopee: 'https://shopee.co.id/batikpekalongan',
    shop_blibli: 'https://blibli.com/batikpekalongan',
    rating: 5.0,
    review_count: 16,
    kurasi_notes: 'Kualitas batik premium, setiap lembar dibuat dengan teliti. Reseller bisa margin 40-60%. Recommended seller!',
    status: 'active',
    images: ['https://images.unsplash.com/photo-1604870756878-0f815606f738?w=600', 'https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=600', 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=600'],
    created_at: '2026-03-10T08:00:00Z',
  },
  {
    id: 'sup-12',
    name: 'Grosir Hijab Amanah Tasikmalaya',
    slug: 'grosir-hijab-amanah-tasikmalaya',
    owner_name: 'Nurul Hidayah',
    email: 'nurul@hijabamanahtsk.com',
    description: 'Grosir hijab dan gamis wanita muslimah. Bahan voile, ceruti, dan jersey. Koleksi 300+ model, update tiap bulan. Harga grosir mulai Rp 25.000/pcs.',
    category_ids: ['cat-4'],
    location_city: 'Tasikmalaya',
    location_province: 'Jawa Barat',
    price_level: 'budget',
    contact_whatsapp: '6281234560012',
    contact_phone: '02659876543',
    contact_address: 'Jl. HZ Mustofa No. 45, Tasikmalaya',
    social_tiktok: 'https://tiktok.com/@hijabamanahtsk',
    social_instagram: 'https://instagram.com/hijab.amanah.tsk',
    social_wa_business: 'https://wa.me/6281234560012',
    shop_shopee: 'https://shopee.co.id/hijabamanahtsk',
    shop_tokopedia: 'https://tokopedia.com/hijabamanahtsk',
    shop_tiktok: 'https://tiktokshop.com/hijabamanahtsk',
    rating: 3.9,
    review_count: 8,
    kurasi_notes: 'Harga paling terjangkau untuk kategori hijab. Cocok untuk reseller pemula dengan modal terbatas.',
    status: 'active',
    images: ['https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600', 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=600'],
    created_at: '2026-03-15T08:00:00Z',
  },
];

export const mockReviews: Review[] = [
  { id: 'rev-1', user_id: 'user-1', reviewer_name: 'Rina W.', supplier_id: 'sup-1', rating: 5, review_text: 'Beras kualitasnya sangat bagus! Pengiriman cepat dan supplier sangat responsif. Sudah order 3x dan selalu memuaskan.', status: 'approved', created_at: '2026-03-20T10:00:00Z' },
  { id: 'rev-2', user_id: 'user-2', reviewer_name: 'Budi S.', supplier_id: 'sup-1', rating: 5, review_text: 'Harga grosir sangat bersaing, beras premium tapi harga terjangkau. Recommended!', status: 'approved', created_at: '2026-03-25T09:00:00Z' },
  { id: 'rev-3', user_id: 'user-3', reviewer_name: 'Dewi A.', supplier_id: 'sup-1', rating: 4, review_text: 'Overall oke, tapi sekali pengiriman agak telat 1 hari. Kualitas beras tetap bagus.', status: 'approved', created_at: '2026-04-01T11:00:00Z' },
  { id: 'rev-4', user_id: 'user-4', reviewer_name: 'Ahmad F.', supplier_id: 'sup-6', rating: 5, review_text: 'Bumbu rempah terbaik untuk usaha catering. Tanpa pengawet dan rasanya autentik.', status: 'approved', created_at: '2026-03-18T14:00:00Z' },
  { id: 'rev-5', user_id: 'user-5', reviewer_name: 'Siti N.', supplier_id: 'sup-6', rating: 5, review_text: 'Stok selalu ready, respon cepat. Bumbu giling masih segar saat sampai.', status: 'approved', created_at: '2026-03-22T16:00:00Z' },
  { id: 'rev-6', user_id: 'user-6', reviewer_name: 'Maya K.', supplier_id: 'sup-11', rating: 5, review_text: 'Batiknya sangat cantik dan kualitas kain premium. Worth every penny!', status: 'approved', created_at: '2026-03-28T08:00:00Z' },
  { id: 'rev-7', user_id: 'user-2', reviewer_name: 'Budi S.', supplier_id: 'sup-4', rating: 5, review_text: 'Sembako lengkap, harga distributor langsung. Pengiriman H+1 untuk Bandung benar-benar terbukti.', status: 'approved', created_at: '2026-03-30T10:00:00Z' },
  { id: 'rev-8', user_id: 'user-3', reviewer_name: 'Dewi A.', supplier_id: 'sup-7', rating: 4, review_text: 'Aksesoris kualitasnya oke untuk harga segitu. Update koleksi memang cepat setiap minggu.', status: 'pending', created_at: '2026-04-07T09:00:00Z' },
  { id: 'rev-9', user_id: 'user-5', reviewer_name: 'Siti N.', supplier_id: 'sup-10', rating: 5, review_text: 'Konveksi terbaik! Jahitan rapi, bahan bagus, dan harga sangat kompetitif untuk MOQ 12 pcs.', status: 'pending', created_at: '2026-04-08T07:00:00Z' },
  { id: 'rev-10', user_id: 'user-1', reviewer_name: 'Rina W.', supplier_id: 'sup-12', rating: 3, review_text: 'Harga murah memang, tapi kualitas jahitan kurang rapi untuk beberapa item.', status: 'pending', created_at: '2026-04-09T08:00:00Z' },
];
